# Pipeline which imports Azure Automation Runbooks from the repo into the Automation Account
# first without approval into DEV
# then with approval to Prod




trigger:
  branches:
    include:
      - '*'


pool:
  vmImage: ubuntu-latest

variables: 
  resourcegroup: 'RG-AutomationCICD'
  dev-automation-account: 'Aut-Account-CICD-dev'
  prod-automation-account: 'Aut-Account-CICD'
  
stages: 
- stage: developmemt
  displayName: 'Import-DEV'
  jobs:
  - deployment: 'importing_new_runbooks_and_delete_old_ones'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self 
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: ADO-SC-Aut-Account-CICD
              scriptType: 'FilePath'
              scriptPath: $(System.DefaultWorkingDirectory)/import-Runbooks-pipeline.ps1
              scriptArguments: > # Use this to avoid newline characters in multiline string
                -rg $(resourcegroup)
                -aa $(dev-automation-account)
              azurePowerShellVersion: latestVersion
              errorActionPreference: stop
            displayName: 'DEV'


- stage: production
  displayName: 'Import-Production'
  jobs:
  - deployment: 'importing_new_runbooks_and_delete_old_ones'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: ADO-SC-Aut-Account-CICD
              scriptType: 'FilePath'
              scriptPath: $(System.DefaultWorkingDirectory)/import-Runbooks-pipeline.ps1
              scriptArguments: > # Use this to avoid newline characters in multiline string
                -rg $(resourcegroup)
                -aa $(prod-automation-account)
              azurePowerShellVersion: latestVersion
              errorActionPreference: stop
            displayName: 'Prod'
            
